
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.github.gmh33;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPERADOR_ASIGNACION_DESPLAZAMIENTO_DERECHA = 24;
  public static final int OPERADOR_PARENTESIS_CERRAR = 14;
  public static final int OPERADOR_ASIGNACION_SUSTRACCION = 19;
  public static final int OPERADOR_MAYOR_IGUAL_QUE = 5;
  public static final int OPERADOR_ASIGNACION_MULTIPLICACION = 20;
  public static final int OPERADOR_MENOR_IGUAL_QUE = 7;
  public static final int OPERADOR_MULTIPLICACION = 11;
  public static final int OPERADOR_ASIGNACION = 17;
  public static final int OPERADOR_SUSTRACCION = 10;
  public static final int OPERADOR_ASIGNACION_DESPLAZAMIENTO_IZQUIERDA = 25;
  public static final int OPERADOR_ASIGNACION_ADICION = 18;
  public static final int OPERADOR_INCREMENTO = 3;
  public static final int OPERADOR_DISMINUCION = 4;
  public static final int OPERADOR_MAYOR_QUE = 6;
  public static final int EOF = 0;
  public static final int DIGITO = 26;
  public static final int OPERADOR = 2;
  public static final int OPERADOR_DESPLAZAMIENTO_DERECHA = 22;
  public static final int OPERADOR_PARENTESIS_ABRIR = 13;
  public static final int error = 1;
  public static final int OPERADOR_DIVISION = 12;
  public static final int OPERADOR_MENOR_QUE = 8;
  public static final int OPERADOR_CORCHETE_ABRIR = 15;
  public static final int OPERADOR_DESPLAZAMIENTO_IZQUIERDA = 23;
  public static final int OPERADOR_ASIGNACION_DIVISION = 21;
  public static final int OPERADOR_ADICION = 9;
  public static final int OPERADOR_CORCHETE_CERRAR = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPERADOR",
  "OPERADOR_INCREMENTO",
  "OPERADOR_DISMINUCION",
  "OPERADOR_MAYOR_IGUAL_QUE",
  "OPERADOR_MAYOR_QUE",
  "OPERADOR_MENOR_IGUAL_QUE",
  "OPERADOR_MENOR_QUE",
  "OPERADOR_ADICION",
  "OPERADOR_SUSTRACCION",
  "OPERADOR_MULTIPLICACION",
  "OPERADOR_DIVISION",
  "OPERADOR_PARENTESIS_ABRIR",
  "OPERADOR_PARENTESIS_CERRAR",
  "OPERADOR_CORCHETE_ABRIR",
  "OPERADOR_CORCHETE_CERRAR",
  "OPERADOR_ASIGNACION",
  "OPERADOR_ASIGNACION_ADICION",
  "OPERADOR_ASIGNACION_SUSTRACCION",
  "OPERADOR_ASIGNACION_MULTIPLICACION",
  "OPERADOR_ASIGNACION_DIVISION",
  "OPERADOR_DESPLAZAMIENTO_DERECHA",
  "OPERADOR_DESPLAZAMIENTO_IZQUIERDA",
  "OPERADOR_ASIGNACION_DESPLAZAMIENTO_DERECHA",
  "OPERADOR_ASIGNACION_DESPLAZAMIENTO_IZQUIERDA",
  "DIGITO"
  };
}

